MVC_Store/MVC_Store/Controllers/CartController.cs
using MVC_Store.Areas.Admin.Data;
using MVC_Store.Models.Data;
using MVC_Store.Models.ViewModels.Cart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace MVC_Store.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session["cart"] as List<CartVM> ?? new List<CartVM>();

            if (cart.Count == 0 || Session["cart"] == null)
            {
                ViewBag.Message = "Ваша корзина пуста";
                return View();
            }
            decimal total = 0m;

            foreach (var item in cart)
            {
                total += item.Total;
            }

            ViewBag.GrandTotal = total;
            CartVM cartVM = new CartVM();

            return View(cart);
        }

        public ActionResult CartPartial()
        {
            CartVM model = new CartVM();

            int qty = 0;

            decimal price = 0m;

            if (Session["cart"] != null)
            {
                var list = (List<CartVM>)Session["cart"];
                foreach (var item in list)
                {
                    qty += item.Quantity;

                    price += item.Quantity * item.Price;
                }

                model.Quantity = qty;
                model.Price = price;
            }
            else
            {
                model.Quantity = 0;
                model.Price = 0m;
            }

            return PartialView("_CartPartial", model);
        }

        public ActionResult AddToCartCard()
        {
            List<CartVM> cart = Session["cart"] as List<CartVM> ?? new List<CartVM>();

            CartVM model = new CartVM();
            int id = 23;
            using (Db db = new Db())
            {
                ProductDTO product = db.Products.Find(id);
                cart.Add(new CartVM()
                {
                    ProductId = product.Id,
                    ProductName = product.Name,
                    Quantity = 1,
                    Price = product.Price,
                    Image = product.ImageName
                }
);
            }
            Session["cart"] = cart;

            return RedirectToAction("");
        }
        public ActionResult AddToCartPartial(int id)
        {

            List<CartVM> cart = Session["cart"] as List<CartVM> ?? new List<CartVM>();

            CartVM model = new CartVM();

            using (Db db = new Db())
            {
                ProductDTO product = db.Products.Find(id);

                var productInCart = cart.FirstOrDefault(y => y.ProductId == id);

                if (productInCart == null)
                {
                    cart.Add(new CartVM()
                    {
                        ProductId = product.Id,
                        ProductName = product.Name,
                        Quantity = 1,
                        Price = product.Price,
                        Image = product.ImageName,
                        Extra = product.Extra
                    }
                    );
                }
                else
                {
                    productInCart.Quantity++;
                }
            }
            int qty = 0;
            decimal price = 0m;

            foreach (var item in cart)
            {
                qty += item.Quantity;
                price += item.Quantity * item.Price;
            }

            model.Quantity = qty;
            model.Price = price;

            Session["cart"] = cart;



            return PartialView("_AddToCartPartial", model);
        }

        public JsonResult IncrementProduct(int productId)
        {
            List<CartVM> cart = Session["cart"] as List<CartVM>;

            using (Db db = new Db())
            {
                CartVM model = cart.FirstOrDefault(y => y.ProductId == productId);

                model.Quantity++;

                var result = new { qty = model.Quantity, price = model.Price 
                };
                return Json(result, JsonRequestBehavior.AllowGet);
            }



        }
        public ActionResult DecrementProduct(int productId)
        {
            List<CartVM> cart = Session["cart"] as List<CartVM>;

            using (Db db = new Db())
            {
                CartVM model = cart.FirstOrDefault(y => y.ProductId == productId);

                if (model.Quantity > 1)
                {
                    model.Quantity--;
                }
                else
                {
                    model.Quantity = 0;
                    cart.Remove(model);
                }

                var result = new { qty = model.Quantity, price = model.Price };

                return Json(result, JsonRequestBehavior.AllowGet);
            }

        }

        public void RemoveProduct(int productId)
        {
            List<CartVM> cart = Session["cart"] as List<CartVM>;

            using (Db db = new Db())
            {
                CartVM model = cart.FirstOrDefault(y => y.ProductId == productId);
                cart.Remove(model);
            }

        }
        public ActionResult PaypalPartial()
        {
            List<CartVM> cart = Session["cart"] as List<CartVM>;



            return PartialView();
        }

        [HttpPost]
        public void PlaceOrder(string date, string time, string adress, string city, string poshta, string cardText, string name, string namelast, string numberPhone, string email, string passwordAcc, string deliv)
        {
            if (numberPhone == null)
            {

                List<CartVM> cart = Session["cart"] as List<CartVM>;

                string userName = User.Identity.Name;

                int orderId = 0;

                using (Db db = new Db())
                {
                    OrderDTO orderDTO = new OrderDTO();

                    var q = db.Users.FirstOrDefault(y => y.Number == userName);
                    int userId = q.Id;
                    orderDTO.UserId = userId;
                    orderDTO.CreatedAt = DateTime.Now;

                    db.Orders.Add(orderDTO);
                    db.SaveChanges();

                    orderId = orderDTO.OrderId;

                    OrderDetailsDTO orderDetailsDTO = new OrderDetailsDTO();

                    foreach (var item in cart)
                    {

                        orderDetailsDTO.ProductId = item.ProductId;
                        orderDetailsDTO.Quantity = item.Quantity;
                        orderDetailsDTO.OrderId = orderId;
                        orderDetailsDTO.UserId = userId;
                        orderDetailsDTO.TimeDelivery = time;
                        orderDetailsDTO.DateDelivery = date;
                        orderDetailsDTO.CityDelivery = city;
                        orderDetailsDTO.AdressDelivery = adress;
                        orderDetailsDTO.DeliveryPoshtaNumber = poshta;
                        orderDetailsDTO.CardDeliveryText = cardText;
                        orderDetailsDTO.DeliveryMethod = deliv;
                        db.OrderDetails.Add(orderDetailsDTO);
                        db.SaveChanges();


                    }


                    

                }



                Session["cart"] = null;

            }
            else
            {
                using (Db db = new Db())
                {
                    if (db.Users.Any(y => y.Number.Equals(numberPhone)))
                    {

                        numberPhone = "";

                    }
                    else
                    {
                        UserDTO userDTO = new UserDTO()
                        {
                            FirstName = name,
                            LastName = namelast,
                            EmailAdress = email,
                            Number = numberPhone,
                            Password = passwordAcc
                        };
                        db.Users.Add(userDTO);

                        db.SaveChanges();

                        int id = userDTO.Id;
                        UserRoleDTO userRoleDTO = new UserRoleDTO()
                        {
                            UserId = id,
                            RoleId = 2
                        };
                        db.UserRoles.Add(userRoleDTO);
                        db.SaveChanges();

                        List<CartVM> cart = Session["cart"] as List<CartVM>;

                        string userName = User.Identity.Name;

                        int orderId = 0;

                        OrderDTO orderDTO = new OrderDTO();


                        int userId = id;
                        orderDTO.UserId = userId;
                        orderDTO.CreatedAt = DateTime.Now;

                        db.Orders.Add(orderDTO);
                        db.SaveChanges();

                        orderId = orderDTO.OrderId;

                        OrderDetailsDTO orderDetailsDTO = new OrderDetailsDTO();

                        foreach (var item in cart)
                        {

                            orderDetailsDTO.ProductId = item.ProductId;
                            orderDetailsDTO.Quantity = item.Quantity;
                            orderDetailsDTO.OrderId = orderId;
                            orderDetailsDTO.UserId = userId;
                            orderDetailsDTO.TimeDelivery = time;
                            orderDetailsDTO.DateDelivery = date;
                            orderDetailsDTO.CityDelivery = city;
                            orderDetailsDTO.AdressDelivery = adress;
                            orderDetailsDTO.DeliveryPoshtaNumber = poshta;
                            orderDetailsDTO.CardDeliveryText = cardText;
                            orderDetailsDTO.DeliveryMethod = deliv;

MVC_Store/MVC_Store/Controllers/PagesController.cs
using MVC_Store.Areas.Admin.Data;
using MVC_Store.Models.Data;
using MVC_Store.Models.ViewModels.Pages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Store.Controllers
{
    public class PagesController : Controller
    {
        // GET: Index/{page}
        public ActionResult Index(string page = "")
        {
            if (page == "")
                page = "home";

            PageVM model;
            PagesDTO dto;

            using (Db db = new Db())
            {
                if (!db.Pages.Any(y => y.Slug.Equals(page)))
                {
                    return RedirectToAction("Index", new { page = "" });
                }
            }

            using (Db db = new Db()) {
                dto = db.Pages.Where(y => y.Slug == page).FirstOrDefault();
            }

            ViewBag.PageTitle = dto.Title;

            if (dto.HasSidebar == true)
            {
                ViewBag.Sidebar = "Да";
            }
            else
            {
                ViewBag.Sidebar = "Нет";
            }

            model = new PageVM(dto);

            return View(model);
        }

        public ActionResult PagesMenuPartial()
        {
            List<PageVM> pageVMList;

            using(Db db = new Db())
            {
                pageVMList = db.Pages.ToArray().OrderBy(y => y.Sorting).Where(y => y.Slug != "home").Select(y => new PageVM(y)).ToList();
            }


            return PartialView("_PagesMenuPartial", pageVMList);
        }

        public ActionResult SidebarPartial()
        {
            SidebarVM model;

            using(Db db = new Db())
            {
                SidebarDTO dto = db.Sidebars.Find(1);

                model = new SidebarVM(dto);
            }


            return PartialView("_SidebarPartial",model);
        }
    }
}

MVC_Store/MVC_Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 101 Shar</title>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="shortcut icon" href="../../Assets/favicon.png" type="image/png">
    <link rel="stylesheet" href="../../Content/css/style_layout.css">
    <link rel="stylesheet" href="../../Content/css/category.css">
    <link rel="stylesheet" href="../../Content/css/adaptiv.css">
    <link rel="stylesheet" href="../../Content/css/Login.css" />
</head>
<body>
    <div class="page">
        <nav class="navbar navbar-expand-lg fixed-top" id="navbar">
            <div class="navbar-container"> 
                <a class="navbar-brand" href="/" title="Главная"><img class="logo_img" src="../../Assets/101_logo.png" /></a>
                <div class="nav-adaptiv">
                    <div class="collapse navbar-collapse" id="navbarText">

                        <div class="navbar-nav mr-auto">
                            <div class="nav-pages">
                                @Html.Action("PagesMenuPartial", "Pages")
                            </div>
                            <div class="nav-pages">
                                @if (Request.IsAuthenticated)
                                {
                                    <div>@Html.ActionLink("Выйти", "Logout", "Account", null, new { @class = "navbar-text", style = "text-decoration: none" })</div>
                                }
                                else
                                {
                                    if (ViewBag.Title == "Войти")
                                    {
                                        <div class="navbar-text">@Html.ActionLink("Войти", "Login", "Account", null, new { @class = "active", style = "text-decoration: none" })</div>
                                    }
                                    else
                                    {
                                        <div>@Html.ActionLink("Войти", "Login", "Account", null, new { @class = "navbar-text", style = "text-decoration: none" })</div>
                                    }
                                }
                            </div>
                            <div class="nav-pages">
                                @if (Request.IsAuthenticated && User.IsInRole("User"))
                                {
                                    if (ViewBag.Title == "User Profile")
                                    {
                                        <div class="active nav-name">@Html.Action("UserNavPartial", "Account", new { area = "" })</div>
                                    }
                                    else
                                    {
                                        <div>@Html.Action("UserNavPartial", "Account", new { area = "" })</div>
                                    }
                                }
                            </div>
                        </div>
                        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <span class="navbar-text">
                                @Html.ActionLink("Админ зона", "Index", "Dashboard", new { area = "Admin" }, null)
                            </span>
                        }
                        else
                        {
                            if (ViewBag.Title != "Cart Details")
                            {
                                <span class="navbar-text">
                                    @Html.Action("CartPartial", "Cart")
                                </span>
                            }

                        }
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                        <div class="navbar-toggler-icon"><img src="../../Assets/nav-menu.png" /></div>
                    </button>
                </div>
            </div>
        </nav>
        <button class="nav-btn open-btn" title="Каталог товаров">
            <img src="../../Assets/squared-menu.png" alt="альтернативный текст">
        </button>
        <div>
            <div class="col-sm-12 col-md-3 list-group navmenu categories" id="mySidenav">
                <div class="nav nav-white ">
                    <button class="nav-btn close-btn">
                        <img src="../../Assets/delete.png" />
                    </button>
                    @Html.Action("CategoryMenuPartial", "Shop")
                </div>
            </div>
            @if (ViewBag.Sidebar == "Да")
            {
                <div class="body_content">
                    @RenderBody()
                </div>
                <div class="body_content">
                    @Html.Action("SidebarPartial", "Pages")
                </div>
            }
            else
            {
                <div>
                    @RenderBody()
                </div>
            }
        </div>
        <footer>
            <div class="footer">
                <div class="footer-logo">
                    <div class="footer-logo_img">
                        <img class="logo_img" src="~/Assets/101_logo.png" />
                    </div>
                    <div class="footer-logo_text">
                        <p>&copy; @DateTime.Now.Year - 101 Shar</p>
                    </div>
                </div>
                <div class="footer-info">
                    <div class="footer-contacts">
                        <div class="footer-life number-life">
                            <a href="tel:+380631421515">+38 063-142-15-15</a>
                        </div>
                        <div class="footer-mts number-mts">
                            <a href="tel:+380661421515">+38 066-142-15-15</a>
                        </div>
                        <div class="footer-kyiv number-kyiv">
                            <a href="tel:+380681421515">+38 068-142-15-15</a>
                        </div>
                    </div>
                    <div class="footer-sosial">
                        <div class="footer-sosial-media">
                            <div class="footer-inst">
                                <a href="https://www.instagram.com/101shar.com.ua/" target="_blank"><img src="~/Assets/instagram.png" /></a>
                            </div>
                            <div class="footer-teleg">
                                <img src="~/Assets/telegram.png" />
                            </div>
                            <div class="footer-email">
                                <a href="mailto:101shar.com@gmail.com"><img src="~/Assets/gmail.png" /></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/scripts")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="../../Scripts/script/script_load.js"></script>
    <script src="../../Scripts/script/script_categories.js"></script>
    <script src="../../Scripts/script/thank_for_order.js"></script>
</body>
</html>